name: PR Checker

on:
  pull_request:
    branches: ["dev"]
    
jobs:
  build:
    name: PR Validator
    runs-on: windows-latest
    
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4.1.7
        
      - name: Setup Dotnet
        uses: actions/setup-dotnet
        with:
          dotnet-version: 8.0
          
      - name: Build Project
        run: dotnet build
          
      - name: Run All Tests
        run: dotnet test --no-build
          
      - name: Finishing Up   
        run: I am done with this job...
  
    